name: "Build"

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  msys2-runtime:
    name: Build msys2-runtime
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Prepare
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          location: D:\msys2
          update: true
      - name: Build
        shell: msys2 {0}
        run: |
          pacman -Sy --needed --noconfirm gcc git patch
          cd msys2-runtime
          makepkg -s --noconfirm
          mv pkg/msys2-runtime/usr/bin/msys-2.0.dll ..
          mv *.pkg.* ..
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: msys2-runtime
          path: |
            msys2-runtime-*.pkg.*
            msys-2.0.dll
          if-no-files-found: error
          retention-days: 1

  mingw-w64-libkqueue:
    name: Build mingw-w64-libkqueue
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Prepare
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          location: D:\msys2
          update: true
      - name: Build
        shell: msys2 {0}
        run: |
          pacman -Sy --needed --noconfirm gcc git patch
          cd mingw-w64-libkqueue
          MINGW_ARCH=clang64 makepkg-mingw -s --noconfirm
          mv pkg/mingw-w64-clang-*-libkqueue/clang64/bin/libkqueue.dll ..
          mv *.pkg.* ..
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mingw-w64-libkqueue
          path: |
            mingw-w64-*-libkqueue-*.pkg.*
            libkqueue.dll
          if-no-files-found: error
          retention-days: 1

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - msys2-runtime
      - mingw-w64-libkqueue
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release
          pattern: "*"
          merge-multiple: true
      - name: Upload artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for i in release/*; do
            gh release upload ${{ github.event.release.tag_name }} $i
          done
